[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MOOSS"
version = "0.1.0"
description = "Multi-Objective Optimization for Synthetic-to-Real Style Transfer"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
license-files = ["LICEN[CS]E*"]


[project.urls]
Homepage = "https://github.com/xxxxx/mooss"
Repository = "https://github.com/xxxxx/mooss"
Documentation = "https://github.com/xxxxx/mooss"

[tool.setuptools]
packages = ["mooss", "CACTIF"]

[tool.black]
line-length = 100
target-version = ["py312"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \__pycache__
  | checkpoints
)/
'''

[tool.isort]
profile = "black"
line_length = 100
skip_gitignore = true

[tool.mypy]
python_version = "3.12.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true
